# Site settings
title: PM2
email: contact@pm2.io
description: > # this means to ignore newlines until "baseurl:"
  Advanced process manager for production Node.js applications. Load balancer, logs facility,
  startup script, micro service management, at a glance.
baseurl: ""
url: "https://pm2.keymetrics.ir"
repo_url: "https://github.com/dadwic/pm2-hive"

sass:
  sass_dir: _sass

markdown: kramdown

exclude: ['node_modules', 'scripts', 'Gemfile', 'Gemfile.lock', 'README.md']

plugins:
  - jekyll-paginate

redcarpet:
  extensions: ['tables', 'no_intra_emphasis', 'autolink']

permalink: /blog/:year/:month/:day/:title
paginate: 1
register_url: https://id.keymetrics.io/api/oauth/register
